services:
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5673:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./apps/backend
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env.runtime


  worker:
    build: ./apps/worker
    profiles: ["local" , "server"]
    depends_on:
      backend:
        condition: service_started
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env.runtime

    volumes:
      - ./simtmp:/simtmp
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build: ./apps/frontend
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      backend:
        condition: service_started

volumes:
  mongo_data:
  rabbitmq_data: